car/urls.py
from typing import List

from django.urls import URLPattern, path

from car import views

urlpatterns: List[URLPattern] = [
    path('dashboard/cars', views.DashboardCarsListView.as_view(), name='dashboard-cars-list-view'),
    path('dashboard/car/create', views.DashboardCarCreateView.as_view(), name='dashboard-car-create-view'),
    path('dashboard/car/<int:pk>', views.DashboardCarDetailView.as_view(), name='dashboard-car-detail-view'),
    path('dashboard/car/<int:pk>/update', views.DashboardCarUpdateView.as_view(), name='dashboard-car-update-view'),
    path('dashboard/car/<int:pk>/delete', views.DashboardCarDeleteView.as_view(), name='dashboard-car-delete-view'),

    path('client/cars', views.ClientCarsListView.as_view(), name='client-cars-list-view'),
    path('client/car/<int:pk>', views.ClientCarDetailView.as_view(), name='client-car-detail-view'),

    path('car/<int:car_id>/service/request', views.service_request, name='car-service-request'),

    path('car/<int:car_id>/availabilities', views.CarAvailabilitiesListView.as_view(), name='car-availabilities-list'),
    path('car/<int:car_id>/availabilities/create', views.CarAvailabilitiesCreateView.as_view(),
         name='car-availabilities-create'),
    path('car/<int:car_id>/availabilities/<int:pk>/update', views.CarAvailabilitiesUpdateView.as_view(),
         name='car-availabilities-update'),
]

car_rental/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('car.urls')),
    path('', include('core.urls')),
    path('', include('rent.urls')),
    path('', include('log.urls')),
    path('', include('schedule.urls')),
]

pwr_pp/urls.py
from django.contrib import admin
from django.urls import path

urlpatterns = [
    path('admin/', admin.site.urls),
]

rent/urls.py
from typing import List

from django.urls import URLPattern, path

from rent import views

urlpatterns: List[URLPattern] = [
    path('dashboard/rents', views.DashboardRentsListView.as_view(), name='dashboard-rents-list-view'),
    path('dashboard/rent/create', views.DashboardRentCreateView.as_view(), name='dashboard-rent-create-view'),
    path('dashboard/rent/<int:pk>', views.DashboardRentDetailView.as_view(), name='dashboard-rent-detail-view'),
    path('dashboard/rent/<int:pk>/update', views.DashboardRentUpdateView.as_view(), name='dashboard-rent-update-view'),
    path('dashboard/rent/<int:pk>/delete', views.DashboardRentDeleteView.as_view(), name='dashboard-rent-delete-view'),

]

rent/models.py
from django.db import models
from django.utils.timezone import now

from car.choices.car_status_choices import CarStatus


class Rent(models.Model):
    rented_by = models.ForeignKey(
        'core.User',
        on_delete=models.DO_NOTHING,
        related_name='rents'
    )
    rented_at = models.DateTimeField(default=now)
    rented_to = models.DateTimeField(
        null=True
    )
    rented_car = models.OneToOneField(
        'car.Car',
        on_delete=models.CASCADE,
        related_name='rent',
    )

    def save(self, *args, **kwargs) -> None:
        create = False if self.pk else True
        super(Rent, self).save(*args, **kwargs)

        if create:
            self.rented_car.status = CarStatus.RENTED_STATUS
            self.rented_car.save()


class Pricing(models.Model):
    daily = models.PositiveIntegerField()
    weekly = models.PositiveIntegerField()
    monthly = models.PositiveIntegerField()

rent/forms/PricingForm.py
from django import forms
from django.forms import ModelForm

from rent.models import Pricing


class PricingForm(ModelForm):
    daily = forms.IntegerField(
        label='Daily rent price',
        widget=forms.NumberInput(attrs={'placeholder': 'Daily rent price...', 'class': 'form-control'})
    )
    weekly = forms.IntegerField(
        label='Weekly rent price',
        widget=forms.NumberInput(attrs={'placeholder': 'Weekly rent price...', 'class': 'form-control'})
    )
    monthly = forms.IntegerField(
        label='Monthly rent price',
        widget=forms.NumberInput(attrs={'placeholder': 'Monthly rent price...', 'class': 'form-control'})
    )

    class Meta:
        model = Pricing
        fields = [
            'daily',
            'weekly',
            'monthly',
        ]

rent/forms/RentForm.py
import datetime

from django import forms
from django.db.models import Q
from django.forms import ModelForm

from car.choices.car_status_choices import CarStatus
from car.models import Car
from core.models import User
from rent.models import Rent


class RentForm(ModelForm):
    rented_at = forms.DateField(
        label='Rented at',
        initial=datetime.date.today(),
        widget=forms.DateInput(attrs={'placeholder': 'Rented at...', 'class': 'form-control', 'type': 'date'})
    )
    rented_to = forms.DateField(
        label='Rented to',
        initial=datetime.date.today(),
        widget=forms.DateInput(attrs={'placeholder': 'Rented to...', 'class': 'form-control', 'type': 'date'})
    )
    rented_by = forms.ModelChoiceField(
        label='Rented by',
        queryset=User.objects.filter(groups__name='client'),
        widget=forms.Select(attrs={'placeholder': 'Production date...', 'class': 'form-control'})
    )
    rented_car = forms.ModelChoiceField(
        label='Rented car',
        queryset=None,
        widget=forms.Select(attrs={'placeholder': 'Rented car...', 'class': 'form-control'})
    )

    class Meta:
        model = Rent
        fields = [
            'rented_at',
            'rented_to',
            'rented_by',
            'rented_car',
        ]

    def __init__(self, *args, **kwargs):
        super(RentForm, self).__init__(*args, **kwargs)

        if hasattr(self.instance, 'rented_car'):
            self.fields['rented_car'].queryset = Car.objects.filter(
                Q(status=CarStatus.READY_TO_RENT_STATUS) | Q(id=self.instance.rented_car.id))
        else:
            self.fields['rented_car'].queryset = Car.objects.filter(status=CarStatus.READY_TO_RENT_STATUS)

rent/views.py
from django.contrib.auth.mixins import PermissionRequiredMixin
from django.urls import reverse
from django.views.generic import ListView, DetailView, CreateView, DeleteView, UpdateView

from rent.forms.RentForm import RentForm
from rent.models import Rent


class DashboardRentsListView(PermissionRequiredMixin, ListView):
    permission_required = 'core.employee_views'
    model = Rent
    template_name = 'rent/dashboard/rents.html'
    queryset = Rent.objects.all()


class DashboardRentDetailView(PermissionRequiredMixin, DetailView):
    permission_required = 'core.employee_views'
    model = Rent
    template_name = 'rent/dashboard/rent.html'


class DashboardRentCreateView(PermissionRequiredMixin, CreateView):
    permission_required = 'core.employee_views'
    form_class = RentForm
    template_name = 'rent/dashboard/create.html'

    def get_success_url(self):
        return reverse('dashboard-rent-detail-view', kwargs={'pk': self.object.pk})  # type: ignore


class DashboardRentUpdateView(PermissionRequiredMixin, UpdateView):
    permission_required = 'core.employee_views'
    model = Rent
    form_class = RentForm
    template_name = 'rent/dashboard/update.html'


class DashboardRentDeleteView(PermissionRequiredMixin, DeleteView):
    permission_required = 'core.employee_views'
    model = Rent

    def get_success_url(self):
        return reverse('dashboard-rents-list-view')

templates/rent/dashboard/create.html
{% extends "layout/dashboard-base.html" %}

{% block title %}
  Add rent
{% endblock %}

{% block breadcumbs %}
  <li class="breadcrumb-item"><a href="{% url 'dashboard-view' %}">Dashboard</a></li>
  <li class="breadcrumb-item"><a href="{% url 'dashboard-rents-list-view' %}">Cars</a></li>
  <li class="breadcrumb-item">Add rent</li>
{% endblock %}

{% block content %}
  <form id="updateRent" method="post">
    {% if form.errors %}
      <div class="alert alert-danger">
        {{ form.errors }}
      </div>
    {% endif %}
    <div class="p-2">
      {% csrf_token %}

      <div class="card mb-4">
        <div class="card-header fw-bold">
          Rent details
        </div>
        <div class="card-body">
          {{ form.rented_by.label }}
          <div class="input-group mb-3">
            {{ form.rented_by }}
            <span class="input-group-text" id="basic-addon2">
                <span class="fas fa-user"></span>
            </span>
          </div>
          {{ form.rented_car.label }}
          <div class="input-group mb-3">
            {{ form.rented_car }}
            <span class="input-group-text" id="basic-addon2">
                <span class="fas fa-car"></span>
            </span>
          </div>
          {{ form.rented_at.label }}
          <div class="input-group mb-3">
            {{ form.rented_at }}
            <span class="input-group-text" id="basic-addon2">
                <span class="fas fa-calendar"></span>
            </span>
          </div>
          {{ form.rented_to.label }}
          <div class="input-group mb-3">
            {{ form.rented_to }}
            <span class="input-group-text" id="basic-addon2">
                <span class="fas fa-calendar"></span>
            </span>
          </div>
        </div>
      </div>
    </div>
  </form>

  <div class="card mb-4">
    <div class="card-footer text-center">
      <a class="mb-2 mr-2 btn btn-shadow ml-3 btn-outline-danger"
         href="{% url 'dashboard-rents-list-view' %}">Cancel</a>
      <button class="mb-2 btn btn-shadow btn-primary" type="submit" form="updateRent" value="Save">Save</button>
    </div>
  </div>

{% endblock %}

templates/rent/dashboard/rent.html
{% extends "layout/dashboard-base.html" %}
{% load template_filetrs %}
{% load static %}

{% block title %}
  #{{ rent.id }} - {{ rent.rented_by.first_name }} {{ rent.rented_by.last_name }}
{% endblock %}

{% block breadcumbs %}
  <li class="breadcrumb-item"><a href="{% url 'dashboard-view' %}">Dashboard</a></li>
  <li class="breadcrumb-item"><a href="{% url 'dashboard-rents-list-view' %}">Rents</a></li>
  <li class="breadcrumb-item">#{{ rent.id }}</li>
{% endblock %}

{% block content %}
  <div class="row">
    <div class="col-12 col-md-6 col-lg-6 col-xl-4 mb-3">
      <div class="card">
        <div class="card-header fw-bold">
          <div class="row">
            <div class="col-11">
              Client details
            </div>
            <div class="col-1">
              <a href="{% url 'dashboard-client-detail-view' rent.rented_by_id %}">
                <i class="fa fa-external-link-alt"></i>
              </a>
            </div>
          </div>
        </div>
        <div class="card-body">
          <div class="row">
            <div class="col-12 col-md-12 col-lg-6 col-xl-6 col-xxl-4 fw-bold">
              First name
            </div>
            <div class="col-12 col-md-12 col-lg-5 col-xl-7">
              {{ user.first_name }}
            </div>
          </div>
          <div class="row">
            <div class="col-12 col-md-12 col-lg-6 col-xl-6 col-xxl-4 fw-bold">
              Last name
            </div>
            <div class="col-12 col-md-12 col-lg-5 col-xl-7">
              {{ user.last_name }}
            </div>
          </div>
          <div class="row">
            <div class="col-12 col-md-12 col-lg-6 col-xl-6 col-xxl-4 fw-bold">
              E-mail
            </div>
            <div class="col-12 col-md-12 col-lg-5 col-xl-7">
              {{ user.email }}
            </div>
          </div>
          <div class="row">
            <div class="col-12 col-md-12 col-lg-6 col-xl-6 col-xxl-4 fw-bold">
              Phone number
            </div>
            <div class="col-12 col-md-12 col-lg-5 col-xl-7">
              {{ user.phone_number }}
            </div>
          </div>
        </div>
      </div>
    </div>

    <div class="col-12 col-md-6 col-lg-6 col-xl-4 mb-3">
      <div class="card">
        <div class="card-header fw-bold">
          <div class="row">
            <div class="col-11">
              Car details
            </div>
            <div class="col-1">
              <a href="{% url 'dashboard-car-detail-view' rent.rented_car_id %}">
                <i class="fa fa-external-link-alt"></i>
              </a>
            </div>
          </div>
        </div>
        <div class="card-body">
          <div class="row">
            <div class="col-12 col-md-12 col-lg-6 col-xl-6 col-xxl-4 fw-bold">
              Manufacturer
            </div>
            <div class="col-12 col-md-12 col-lg-5 col-xl-7">
              {{ rent.rented_car.manufacturer }}
            </div>
          </div>
          <div class="row">
            <div class="col-12 col-md-12 col-lg-6 col-xl-6 col-xxl-4 fw-bold">
              Model
            </div>
            <div class="col-12 col-md-12 col-lg-5 col-xl-7">
              {{ rent.rented_car.model }}
            </div>
          </div>
          <div class="row">
            <div class="col-12 col-md-12 col-lg-6 col-xl-6 col-xxl-4 fw-bold">
              Mileage
            </div>
            <div class="col-12 col-md-12 col-lg-5 col-xl-7">
              {{ rent.rented_car.mileage }}
            </div>
          </div>
          <div class="row">
            <div class="col-12 col-md-12 col-lg-6 col-xl-6 col-xxl-4 fw-bold">
              Production
            </div>
            <div class="col-12 col-md-12 col-lg-5 col-xl-7">
              {{ rent.rented_car.production_date }}
            </div>
          </div>
        </div>
      </div>
    </div>

    <div class="col-12 col-md-6 col-lg-6 col-xl-4 mb-3">
      <div class="card">
        <div class="card-header fw-bold">
          <div class="row">
            <div class="col-11">
              Rent details
            </div>
            <div class="col-1">
            </div>
          </div>
        </div>
        <div class="card-body">
          <div class="row">
            <div class="col-12 col-md-12 col-lg-6 col-xl-6 col-xxl-4 fw-bold">
              Rented at / to
            </div>
            <div class="col-12 col-md-12 col-lg-5 col-xl-7">
              {{ rent.rented_at }} / {{ rent.rented_to }}
            </div>
          </div>
          <div class="row">
            <div class="col-12 col-md-12 col-lg-6 col-xl-6 col-xxl-4 fw-bold">
              Daily price
            </div>
            <div class="col-12 col-md-12 col-lg-5 col-xl-7">
              {{ rent.rented_car.pricing.daily }} zł
            </div>
          </div>
          <div class="row">
            <div class="col-12 col-md-12 col-lg-6 col-xl-6 col-xxl-4 fw-bold">
              Weekly price
            </div>
            <div class="col-12 col-md-12 col-lg-5 col-xl-7">
              {{ rent.rented_car.pricing.weekly }} zł
            </div>
          </div>
          <div class="row">
            <div class="col-12 col-md-12 col-lg-6 col-xl-6 col-xxl-4 fw-bold">
              Monthly
            </div>
            <div class="col-12 col-md-12 col-lg-5 col-xl-7">
              {{ rent.rented_car.pricing.monthly }} zł
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
{% endblock %}

templates/rent/dashboard/rents.html
{% extends "layout/dashboard-base.html" %}


{% block title %}
  Rents
{% endblock %}

{% block breadcumbs %}
  <li class="breadcrumb-item"><a href="{% url 'dashboard-view' %}">Dashboard</a></li>
  <li class="breadcrumb-item">Rents</li>
{% endblock %}

{% block content %}
  <div class="table-responsive">
    <table class="table table-striped table-hover">
      <thead>
      <tr class="col-12">
        <th class="col-md-1">
          Id
        </th>
        <th class="col-md-4">
          Car
        </th>
        <th class="col-md-4">
          Client
        </th>
        <th class="col-md-3 text-end">
          <a href="{% url 'dashboard-rent-create-view' %}">
            <i class="fas fa-plus"></i>
          </a>
        </th>
      </tr>
      </thead>
      <tbody>
      {% for rent in rent_list %}
        <tr>
          <td class="col-md-1">
            {{ rent.id }}
          </td>
          <td class="col-md-1">
            <a href="{% url 'dashboard-car-detail-view' rent.rented_car_id %}">
              {{ rent.rented_car }}
            </a>
          </td>
          <td class="col-md-1">
            <a href="#">
              <a href="{% url 'dashboard-client-detail-view' rent.rented_by_id %}">
                {{ rent.rented_by }}
              </a>
            </a>
          </td>
          <td class="col-md-1 text-end">
            <a href="{% url 'dashboard-rent-detail-view' rent.pk %}">
              <i class="fas fa-external-link-alt"></i>
            </a>
            <a href="{% url 'dashboard-rent-update-view' rent.pk %}">
              <i class="fas fa-pen text-info"></i>
            </a>
            <a href="{% url 'dashboard-rent-delete-view' rent.pk %}">
              <i class="fas fa-trash text-danger"></i>
            </a>
          </td>
        </tr>
      {% endfor %}
      </tbody>
    </table>
  </div>
{% endblock %}

templates/rent/dashboard/update.html
{% extends "layout/dashboard-base.html" %}

{% block title %}
  Update rent
{% endblock %}

{% block breadcumbs %}
  <li class="breadcrumb-item"><a href="{% url 'dashboard-view' %}">Dashboard</a></li>
  <li class="breadcrumb-item"><a href="{% url 'dashboard-rents-list-view' %}">Rents</a></li>
  <li class="breadcrumb-item">Update - #{{ rent.id }}</li>
{% endblock %}

{% block content %}
  <form id="updateRent" method="post">
    {% if form.errors %}
      <div class="alert alert-danger">
        {{ form.errors }}
      </div>
    {% endif %}
    <div class="p-2">
      {% csrf_token %}

      <div class="card mb-4">
        <div class="card-header fw-bold">
          Rent details
        </div>
        <div class="card-body">
          {{ form.rented_by.label }}
          <div class="input-group mb-3">
            {{ form.rented_by }}
            <span class="input-group-text" id="basic-addon2">
                <span class="fas fa-user"></span>
            </span>
          </div>
          {{ form.rented_car.label }}
          <div class="input-group mb-3">
            {{ form.rented_car }}
            <span class="input-group-text" id="basic-addon2">
                <span class="fas fa-car"></span>
            </span>
          </div>
          {{ form.rented_at.label }}
          <div class="input-group mb-3">
            {{ form.rented_at }}
            <span class="input-group-text" id="basic-addon2">
                <span class="fas fa-calendar"></span>
            </span>
          </div>
          {{ form.rented_to.label }}
          <div class="input-group mb-3">
            {{ form.rented_to }}
            <span class="input-group-text" id="basic-addon2">
                <span class="fas fa-calendar"></span>
            </span>
          </div>
        </div>
      </div>
    </div>
  </form>

  <div class="card mb-5">
    <div class="card-footer text-center">
      <a class="mb-2 mr-2 btn btn-shadow ml-3 btn-outline-danger"
         href="{% url 'dashboard-rents-list-view' %}">Cancel</a>
      <button class="mb-2 btn btn-shadow btn-primary" type="submit" form="updateRent" value="Save">Save</button>
    </div>
  </div>

{% endblock %}