car/urls.py
from typing import List

from django.urls import URLPattern, path

from car import views

urlpatterns: List[URLPattern] = [
    path('dashboard/cars', views.DashboardCarsListView.as_view(), name='dashboard-cars-list-view'),
    path('dashboard/car/create', views.DashboardCarCreateView.as_view(), name='dashboard-car-create-view'),
    path('dashboard/car/<int:pk>', views.DashboardCarDetailView.as_view(), name='dashboard-car-detail-view'),
    path('dashboard/car/<int:pk>/update', views.DashboardCarUpdateView.as_view(), name='dashboard-car-update-view'),
    path('dashboard/car/<int:pk>/delete', views.DashboardCarDeleteView.as_view(), name='dashboard-car-delete-view'),

    path('client/cars', views.ClientCarsListView.as_view(), name='client-cars-list-view'),
    path('client/car/<int:pk>', views.ClientCarDetailView.as_view(), name='client-car-detail-view'),

    path('car/<int:car_id>/service/request', views.service_request, name='car-service-request'),

    path('car/<int:car_id>/availabilities', views.CarAvailabilitiesListView.as_view(), name='car-availabilities-list'),
    path('car/<int:car_id>/availabilities/create', views.CarAvailabilitiesCreateView.as_view(),
         name='car-availabilities-create'),
    path('car/<int:car_id>/availabilities/<int:pk>/update', views.CarAvailabilitiesUpdateView.as_view(),
         name='car-availabilities-update'),
]

car_rental/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('car.urls')),
    path('', include('core.urls')),
    path('', include('rent.urls')),
    path('', include('log.urls')),
    path('', include('schedule.urls')),
]

pwr_pp/urls.py
from django.contrib import admin
from django.urls import path

urlpatterns = [
    path('admin/', admin.site.urls),
]

car/models.py
import datetime
import uuid

from django.db import models
from django.db.models import QuerySet
from django.utils import timezone

from car.choices.body_type_choices import BodyType
from car.choices.car_status_choices import CarStatus
from car.choices.drivetrain_type_choices import DrivetrainType
from car.choices.fuel_type_choices import FuelType
from car.choices.transmission_type_choices import TransmissionType
from car_rental import settings
from core.checkers.user_checkers import has_group
from core.models import Address
from core.models_mixins.TimeStampMixin import TimeStampMixin
from log.models import ServiceLog


class RestrictedCarManager(models.Manager):
    def get_query(self, user) -> 'QuerySet[Car]':
        if user:
            if has_group(user, 'employee'):
                return self.all()
            else:
                return self.filter(rent__rented_by=user)

        return self.none()


class Car(TimeStampMixin):
    objects = RestrictedCarManager()

    manufacturer = models.CharField(max_length=80)
    model = models.CharField(max_length=80)
    mileage = models.IntegerField(default=1000)
    production_date = models.DateField()
    registration_number = models.CharField(max_length=10)
    air_conditioning = models.BooleanField(default=False)
    transmission_type = models.CharField(max_length=15, choices=TransmissionType.TRANSMISSION_TYPE_CHOICES)
    status = models.CharField(default="ready to rent", max_length=15, choices=CarStatus.CAR_STATUS_CHOICES)
    body_type = models.CharField(max_length=20, choices=BodyType.BODY_TYPE_CHOICES)
    drivetrain_type = models.CharField(max_length=25, choices=DrivetrainType.DRIVETRAIN_TYPE_CHOICES)
    seats = models.PositiveIntegerField()
    trunk_volume = models.PositiveIntegerField()
    token = models.UUIDField(primary_key=False, default=uuid.uuid4)
    engine = models.ForeignKey(
        'car.Engine',
        on_delete=models.DO_NOTHING,
        related_name='cars'
    )
    pricing = models.ForeignKey(
        'rent.Pricing',
        on_delete=models.DO_NOTHING,
        related_name='car',
        null=True,
    )
    servicing = models.ForeignKey(
        'car.Servicing',
        on_delete=models.DO_NOTHING,
        related_name='car',
        null=True,
    )
    created_by = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        on_delete=models.DO_NOTHING,
        related_name='created_cars'
    )

    def save(self, *args, **kwargs) -> None:
        create = False if self.pk else True
        super(Car, self).save(*args, **kwargs)

        if create:
            if self.servicing:
                ServiceLog.objects.create(
                    car=self,
                    action="Car added to rental system.",
                    description="",
                    mileage=self.mileage,
                    next_service_mileage=self.mileage + int(self.servicing.service_mileage_interval),
                    next_service_date=datetime.date(self.created_at.year + 1, self.created_at.month,
                                                    self.created_at.day),
                    created_by=self.created_by,
                )

    def last_service(self) -> ServiceLog:
        return self.services.latest('created_at')

    def next_service_mileage(self) -> int:
        return self.last_service().next_service_mileage

    def days_to_service(self) -> int:
        return (self.last_service().next_service_date - datetime.date.today()).days

    def kilometers_to_service(self) -> int:
        kilometers_to_service = self.last_service().next_service_mileage - int(self.mileage)
        return kilometers_to_service

    def __str__(self) -> str:
        return "#%d - %s %s - %s" % (self.pk, self.manufacturer, self.model, self.registration_number)


class Engine(models.Model):
    volume = models.CharField(max_length=50, null=True)
    horsepower = models.PositiveIntegerField()
    fuel_type = models.CharField(max_length=20, choices=FuelType.FUEL_TYPES_CHOICES)

    def __str__(self):
        return "#%d - %s cc, %s hp, %s" % (self.pk, self.volume, self.horsepower, self.fuel_type)


class Servicing(models.Model):
    service_mileage_interval = models.PositiveIntegerField(default=15000)
    insured_date = models.DateField(default=timezone.now)
    technical_overview_date = models.DateField(default=timezone.now)


class ScheduleService(TimeStampMixin):
    car = models.ForeignKey('car.Car', on_delete=models.CASCADE, related_name='scheduled_services')
    address = models.ForeignKey('core.Address', on_delete=models.CASCADE, related_name='scheduled_services')
    ended_at = models.DateTimeField(null=True)

    def save(self, *args, **kwargs) -> None:
        address = Address.objects.filter(is_service=True).order_by('?').first()

        if address:
            self.address = address

        super(ScheduleService, self).save(*args, **kwargs)


class CompanyCar(models.Model):
    name = models.CharField(max_length=80)
    capacity = models.IntegerField()


class Availability(TimeStampMixin):
    start = models.DateTimeField()
    end = models.DateTimeField()
    address = models.ForeignKey('core.Address', on_delete=models.CASCADE, related_name='availabilities')
    car = models.ForeignKey('car.Car', on_delete=models.CASCADE, related_name='availabilities')
    service = models.ForeignKey('car.ScheduleService', on_delete=models.DO_NOTHING, related_name='availabilities')

    class Meta:
        ordering = ['created_at']

    def save(self, *args, **kwargs) -> None:
        service = self.car.scheduled_services.filter(ended_at=None).first()

        if service:
            self.service = service
        super(Availability, self).save(*args, **kwargs)

car/forms/CarAvailabilityForm.py
import datetime

from django import forms
from django.forms import ModelForm

from car.models import Car, Availability
from core.models import Address


class CarAvailabilityForm(ModelForm):
    start = forms.DateTimeField(
        label='Start',
        initial=datetime.date.today(),
        localize=True,
        widget=forms.DateTimeInput(
            attrs={'placeholder': 'Start...', 'class': 'form-control', 'type': 'datetime-local'},
            format="%Y-%m-%dT%H:%M")
    )
    end = forms.DateTimeField(
        label='End',
        initial=datetime.date.today(),
        localize=True,
        widget=forms.DateTimeInput(attrs={'placeholder': 'End...', 'class': 'form-control', 'type': 'datetime-local'},
                                   format="%Y-%m-%dT%H:%M")
    )
    car = forms.ModelChoiceField(
        label='Car',
        queryset=Car.objects.all(),
        disabled=True,
        widget=forms.Select(attrs={'placeholder': 'Car...', 'class': 'form-control'})
    )
    address = forms.ModelChoiceField(
        label='Address',
        queryset=Address.objects.none(),
        widget=forms.Select(attrs={'placeholder': 'Address...', 'class': 'form-control'})
    )

    class Meta:
        model = Availability
        fields = [
            'start',
            'end',
            'car',
            'address'
        ]

    def __init__(self, user, car, *args, **kwargs):
        super(CarAvailabilityForm, self).__init__(*args, **kwargs)

        self.fields['car'].queryset = Car.objects.get_query(user=user)
        self.fields['car'].initial = Car.objects.get_query(user=user).get(id=car.id)

        self.fields['address'].queryset = Address.objects.filter(user=car.rent.rented_by)

car/forms/ServiceRequestForm.py
from django import forms
from django.forms import ModelForm

from car.models import Servicing


class ServiceRequestForm(ModelForm):
    message = forms.CharField(
        label='Reason of service request',
        widget=forms.Textarea(attrs={'placeholder': 'Reason of service request...', 'class': 'form-control'})
    )

    class Meta:
        model = Servicing
        fields = [
            'message',
        ]

car/views.py
from typing import Dict, Any

from django.contrib.auth.mixins import PermissionRequiredMixin, LoginRequiredMixin
from django.db.models import QuerySet
from django.http import Http404, HttpResponseRedirect
from django.shortcuts import render
from django.urls import reverse
from django.views.generic import ListView, DetailView, CreateView, DeleteView, UpdateView

from car.choices.car_status_choices import CarStatus
from car.forms.CarAvailabilityForm import CarAvailabilityForm
from car.forms.CarForm import CarForm
from car.forms.ServiceRequestForm import ServiceRequestForm
from car.models import Car, Engine, Servicing, Availability
from core.checkers.user_checkers import has_group
from log.messages.messages import LogMessage
from log.models import MessageLog
from rent.models import Pricing


class DashboardCarsListView(PermissionRequiredMixin, ListView):
    permission_required = 'core.employee_views'
    model = Car
    template_name = 'car/dashboard/cars.html'
    queryset = Car.objects.all()


class ClientCarsListView(PermissionRequiredMixin, ListView):
    permission_required = 'core.client_views'
    model = Car
    template_name = 'car/client/cars.html'

    def get_queryset(self) -> QuerySet:
        if self.request.user.is_authenticated:
            return Car.objects.filter(rent__rented_by=self.request.user)

        raise Http404


class DashboardCarDetailView(PermissionRequiredMixin, DetailView):
    permission_required = 'core.employee_views'
    model = Car
    template_name = 'car/dashboard/car.html'


class ClientCarDetailView(PermissionRequiredMixin, DetailView):
    permission_required = 'core.client_views'
    model = Car
    template_name = 'car/client/car.html'

    def get_queryset(self) -> QuerySet:
        return Car.objects.get_query(self.request.user)


class DashboardCarCreateView(PermissionRequiredMixin, CreateView):
    permission_required = 'core.employee_views'
    form_class = CarForm
    template_name = 'car/dashboard/create.html'

    def form_valid(self, form):
        obj = form.save(commit=False)

        engine: Engine = Engine.objects.create(
            volume=form.cleaned_data.get("volume"),
            horsepower=form.cleaned_data.get("horsepower"),
            fuel_type=form.cleaned_data.get("fuel_type"),
        )

        pricing: Pricing = Pricing.objects.create(
            daily=form.cleaned_data.get("daily"),
            weekly=form.cleaned_data.get("weekly"),
            monthly=form.cleaned_data.get("monthly"),
        )

        servicing: Servicing = Servicing.objects.create(
            service_mileage_interval=form.cleaned_data.get("service_mileage_interval"),
            insured_date=form.cleaned_data.get("insured_date"),
            technical_overview_date=form.cleaned_data.get("technical_overview_date"),
        )

        obj.engine = engine
        obj.pricing = pricing
        obj.servicing = servicing
        obj.created_by = self.request.user
        obj.updated_by = self.request.user

        return super(DashboardCarCreateView, self).form_valid(form)

    def get_success_url(self):
        return reverse('dashboard-car-detail-view', kwargs={'pk': self.object.pk})  # type: ignore


class DashboardCarUpdateView(PermissionRequiredMixin, UpdateView):
    permission_required = 'core.employee_views'
    model = Car
    form_class = CarForm
    template_name = 'car/dashboard/update.html'

    def get_initial(self) -> Dict[str, Any]:
        car = Car.objects.get(id=self.kwargs['pk'])
        car_dict = car.__dict__
        car_dict.update(car.engine.__dict__)
        car_dict.update(car.pricing.__dict__)
        car_dict.update(car.servicing.__dict__)

        return car_dict

    def form_valid(self, form):
        obj = form.save(commit=False)

        obj.engine.volume = int(form.cleaned_data.get("volume"))
        obj.engine.horsepower = int(form.cleaned_data.get("horsepower"))
        obj.engine.fuel_type = form.cleaned_data.get("fuel_type")
        obj.engine.save()

        obj.pricing.daily = int(form.cleaned_data.get("daily"))
        obj.pricing.weekly = int(form.cleaned_data.get("weekly"))
        obj.pricing.monthly = int(form.cleaned_data.get("monthly"))
        obj.pricing.save()

        obj.servicing.service_mileage_interval = int(form.cleaned_data.get("service_mileage_interval"))
        obj.servicing.insured_date = form.cleaned_data.get("insured_date")
        obj.servicing.technical_overview_date = form.cleaned_data.get("technical_overview_date")
        obj.servicing.save()

        obj.updated_by = self.request.user

        return super(DashboardCarUpdateView, self).form_valid(form)

    def get_success_url(self):
        return reverse('dashboard-car-detail-view', kwargs={'pk': self.object.pk})  # type: ignore


class DashboardCarDeleteView(PermissionRequiredMixin, DeleteView):
    permission_required = 'core.employee_views'
    model = Car

    def get_success_url(self):
        return reverse('dashboard-cars-list-view')


class CarAvailabilitiesListView(LoginRequiredMixin, ListView):
    model = Availability
    template_name = 'car/availability/availabilities.html'

    def get_queryset(self):
        return Availability.objects.filter(car_id=self.kwargs['car_id'])

    def get_context_data(self, **kwargs):
        context = super(CarAvailabilitiesListView, self).get_context_data(**kwargs)
        context['car'] = Car.objects.get(id=self.kwargs['car_id'])

        return context


class CarAvailabilitiesCreateView(LoginRequiredMixin, CreateView):
    form_class = CarAvailabilityForm
    template_name = 'car/availability/create.html'

    def get_form_kwargs(self, **kwargs):
        kwargs = super(CarAvailabilitiesCreateView, self).get_form_kwargs()
        kwargs['user'] = self.request.user
        kwargs['car'] = Car.objects.get(id=self.kwargs['car_id'])

        return kwargs

    def get_context_data(self, **kwargs):
        context = super(CarAvailabilitiesCreateView, self).get_context_data(**kwargs)
        context['car'] = Car.objects.get(id=self.kwargs['car_id'])

        return context

    def get_success_url(self):
        return reverse('car-availabilities-list', kwargs={'car_id': self.object.car.id})  # type: ignore


class CarAvailabilitiesUpdateView(LoginRequiredMixin, UpdateView):
    model = Availability
    form_class = CarAvailabilityForm
    template_name = 'car/availability/update.html'

    def get_success_url(self):
        return reverse('car-availabilities-list', kwargs={'car_id': self.object.car.id})  # type: ignore

    def get_form_kwargs(self, **kwargs):
        kwargs = super(CarAvailabilitiesUpdateView, self).get_form_kwargs()
        kwargs['user'] = self.request.user
        kwargs['car'] = Car.objects.get(id=self.kwargs['car_id'])

        return kwargs

    def get_context_data(self, **kwargs):
        context = super(CarAvailabilitiesUpdateView, self).get_context_data(**kwargs)
        context['car'] = Car.objects.get(id=self.kwargs['car_id'])

        return context


def service_request(request, car_id: int):
    cars: QuerySet[Car] = Car.objects.get_query(request.user)
    car: Car = cars.get(id=car_id)

    if request.method == 'POST':
        form = ServiceRequestForm(request.POST)
        if form.is_valid():
            if car:
                car.status = CarStatus.NEED_SERVICE_STATUS

                if has_group(request.user, 'employee'):
                    action = LogMessage.SERVICE_REQUESTED_BY_EMPLOYEE
                else:
                    action = LogMessage.SERVICE_REQUESTED_BY_CLIENT

                car.messages.add(MessageLog(
                    car=car,
                    action=action,
                    message=request.POST.get('message', ''),
                    created_by=request.user,
                ),
                    bulk=False
                )

                car.save()

            return HttpResponseRedirect(request.POST.get('next', '/'))
    else:
        form = ServiceRequestForm()

    return render(request, 'car/car_confirm_service_request.html', {'form': form, 'car': car})

templates/car/client/car.html
{% extends "layout/dashboard-base.html" %}
{% load template_filetrs %}
{% load static %}

{% block title %}
  {{ car }}
{% endblock %}

{% block breadcumbs %}
  <li class="breadcrumb-item"><a href="{% url 'dashboard-view' %}">{{ user.first_name }} {{ user.last_name }}</a></li>
  <li class="breadcrumb-item"><a href="{% url 'client-cars-list-view' %}">Cars</a></li>
  <li class="breadcrumb-item">{{ car }}</li>
{% endblock %}

{% block content %}
  <div class="row">
    <div class="col-12 col-md-6 col-lg-6 col-xl-4 mb-3">
      <div class="card">
        <div class="card-header fw-bold">
          Car details
        </div>
        <div class="card-body">
          <div class="row">
            <div class="col-12 col-md-12 col-lg-6 col-xl-6 col-xxl-4 fw-bold">
              Manufacturer
            </div>
            <div class="col-12 col-md-12 col-lg-5 col-xl-7">
              {{ car.manufacturer }}
            </div>
          </div>
          <div class="row">
            <div class="col-12 col-md-12 col-lg-6 col-xl-6 col-xxl-4 fw-bold">
              Model
            </div>
            <div class="col-12 col-md-12 col-lg-5 col-xl-7">
              {{ car.model }}
            </div>
          </div>
          <div class="row">
            <div class="col-12 col-md-12 col-lg-6 col-xl-6 col-xxl-4 fw-bold">
              Mileage
            </div>
            <div class="col-12 col-md-12 col-lg-5 col-xl-7">
              {{ car.mileage }}
            </div>
          </div>
          <div class="row">
            <div class="col-12 col-md-12 col-lg-6 col-xl-6 col-xxl-4 fw-bold">
              Production
            </div>
            <div class="col-12 col-md-12 col-lg-5 col-xl-7">
              {{ car.production_date }}
            </div>
          </div>
        </div>
      </div>
    </div>

    <div class="col-12 col-md-6 col-lg-6 col-xl-4 mb-3">
      <div class="card">
        <div class="card-header fw-bold">
          Engine details
        </div>
        <div class="card-body">
          <div class="row">
            <div class="col-12 col-md-12 col-lg-6 col-xl-6 col-xxl-4 fw-bold">
              Volume
            </div>
            <div class="col-12 col-md-12 col-lg-5 col-xl-7">
              {{ car.engine.volume }} cm<sup>3</sup>
            </div>
          </div>
          <div class="row">
            <div class="col-12 col-md-12 col-lg-6 col-xl-6 col-xxl-4 fw-bold">
              Horsepower
            </div>
            <div class="col-12 col-md-12 col-lg-5 col-xl-7">
              {{ car.engine.horsepower }} HP
            </div>
          </div>
          <div class="row">
            <div class="col-12 col-md-12 col-lg-6 col-xl-6 col-xxl-4 fw-bold">
              Fuel type
            </div>
            <div class="col-12 col-md-12 col-lg-5 col-xl-7">
              {{ car.engine.get_fuel_type_display }}
            </div>
          </div>
          <div class="row">
            <div class="col-12 col-md-12 col-lg-6 col-xl-6 col-xxl-4 fw-bold">
              Transmission type
            </div>
            <div class="col-12 col-md-12 col-lg-5 col-xl-7">
              {{ car.get_transmission_type_display }}
            </div>
          </div>
        </div>
      </div>
    </div>

    <div class="col-12 col-md-6 col-lg-6 col-xl-4 mb-3">
      <div class="card">
        <div class="card-header fw-bold">
          Details
        </div>
        <div class="card-body">
          <div class="row">
            <div class="col-12 col-md-12 col-lg-6 col-xl-6 col-xxl-4 fw-bold">
              Air conditioning
            </div>
            <div class="col-12 col-md-12 col-lg-5 col-xl-7">
              {{ car.air_conditioning }}
            </div>
          </div>
          <div class="row">
            <div class="col-12 col-md-12 col-lg-6 col-xl-6 col-xxl-4 fw-bold">
              Body type
            </div>
            <div class="col-12 col-md-12 col-lg-5 col-xl-7">
              {{ car.get_body_type_display }}
            </div>
          </div>
          <div class="row">
            <div class="col-12 col-md-12 col-lg-6 col-xl-6 col-xxl-4 fw-bold">
              Drivetrain type
            </div>
            <div class="col-12 col-md-12 col-lg-5 col-xl-7">
              {{ car.get_drivetrain_type_display }}
            </div>
          </div>
          <div class="row">
            <div class="col-12 col-md-12 col-lg-6 col-xl-6 col-xxl-4 fw-bold">
              Seats / Luggage
            </div>
            <div class="col-12 col-md-12 col-lg-5 col-xl-7">
              {{ car.seats }} / {{ car.trunk_volume }}
            </div>
          </div>
        </div>
      </div>
    </div>

    <div class="col-12 col-md-6 col-lg-6 col-xl-4 mb-3">
      <div class="card">
        <div class="card-header fw-bold">
          <div class="row">
            <div class="col-6">
              Servicing
            </div>
            {% if car.status != 'need service' %}
              <div class="col-6 text-end">
                <a href="{% url 'car-service-request' car.pk %}">
                  Request service
                </a>
              </div>
            {% else %}
              <div class="col-6 text-end text-danger">
                <a href="{% url 'car-availabilities-list' car.id %}" class="text-danger text-uppercase">
                  Add Pickup availabilities
                </a>
              </div>
            {% endif %}
          </div>
        </div>
        <div class="card-body">
          <div class="row">
            <div class="col-12 col-md-12 col-lg-6 col-xl-6 col-xxl-4 fw-bold">
              Service interval
            </div>
            <div class="col-12 col-md-12 col-lg-5 col-xl-7">
              {{ car.servicing.service_mileage_interval }} km
            </div>
          </div>
          <div class="row">
            <div class="col-12 col-md-12 col-lg-6 col-xl-6 col-xxl-4 fw-bold">
              To next service
            </div>
            <div class="col-12 col-md-12 col-lg-5 col-xl-7">
              {{ car.last_service.next_service_mileage|subtract:car.mileage }} km
            </div>
          </div>
          <div class="row">
            <div class="col-12 col-md-12 col-lg-6 col-xl-6 col-xxl-4 fw-bold">
              Overview date
            </div>
            <div class="col-12 col-md-12 col-lg-5 col-xl-7">
              {{ car.servicing.technical_overview_date }}
            </div>
          </div>
          <div class="row">
            <div class="col-12 col-md-12 col-lg-6 col-xl-6 col-xxl-4 fw-bold">
              Insurance date
            </div>
            <div class="col-12 col-md-12 col-lg-5 col-xl-7">
              {{ car.servicing.insured_date }}
            </div>
          </div>
        </div>
      </div>
    </div>
    <div class="col-12 col-md-6 col-lg-6 col-xl-4 mb-3">
      <div class="card">
        <div class="card-header fw-bold">
          Pricing
        </div>
        <div class="card-body">
          <div class="row">
            <div class="col-12 col-md-12 col-lg-6 col-xl-6 col-xxl-4 fw-bold">
              Daily
            </div>
            <div class="col-12 col-md-12 col-lg-5 col-xl-7">
              {{ car.pricing.daily }} PLN
            </div>
          </div>
          <div class="row">
            <div class="col-12 col-md-12 col-lg-6 col-xl-6 col-xxl-4 fw-bold">
              Weekly
            </div>
            <div class="col-12 col-md-12 col-lg-5 col-xl-7">
              {{ car.pricing.weekly }} PLN
            </div>
          </div>
          <div class="row">
            <div class="col-12 col-md-12 col-lg-6 col-xl-6 col-xxl-4 fw-bold">
              Monthly
            </div>
            <div class="col-12 col-md-12 col-lg-5 col-xl-7">
              {{ car.pricing.monthly }} PLN
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
  <br>
  <h3>Services</h3>
  <hr>
  <div class="table-responsive">
    <table class="table table-striped table-hover mb-6">
      <thead>
      <tr>
        <th>Date</th>
        <th>Mileage</th>
        <th>Next service</th>
        <th>Action</th>
        <th>Description</th>
      </tr>
      </thead>
      <tbody>
      {% for service in car.services.all %}
        <tr>
          <td>
            {{ service.created_at }}
          </td>
          <td>
            {{ service.mileage }}
          </td>
          <td>
            {{ service.next_service_mileage }} / {{ service.next_service_date }}
          </td>
          <td>
            {{ service.action }}
          </td>
          <td>
            {{ service.description }}
          </td>
        </tr>
      {% endfor %}
      </tbody>
    </table>
  </div>
  <br>

  {% if car.logs.count > 0 %}
    <h3>Daily logs</h3>
    <hr>
    <div class="table-responsive">
      <table class="table table-hover table-striped mb-4">
        <thead>
        <tr>
          <th>Date</th>
          <th>Mileage</th>
          <th>Difference to previous day</th>
        </tr>
        </thead>
        <tbody>
        {% for log in car.logs.all %}
          <tr>
            <td>
              {{ log.created_at }}
            </td>
            <td>
              {{ log.mileage }}
            </td>
            <td>
              {{ log.difference_to_previous_day }}
            </td>
          </tr>
        {% endfor %}
        </tbody>
      </table>
    </div>
  {% endif %}

{% endblock %}

templates/car/client/cars.html
{% extends "layout/dashboard-base.html" %}


{% block title %}
  Cars
{% endblock %}

{% block breadcumbs %}
  <li class="breadcrumb-item"><a href="{% url 'dashboard-view' %}">{{ user.first_name }} {{ user.last_name }}</a></li>
  <li class="breadcrumb-item">Cars</li>
{% endblock %}

{% block content %}
  <div class="table-responsive">
    <table class="table table-striped table-hover">
      <thead>
      <tr class="col-12">
        <th class="col-md-1">
          Registration number
        </th>
        <th class="col-md-1">
          Manufacturer
        </th>
        <th class="col-md-1">
          Model
        </th>
        <th class="col-md-1">
          Mileage
        </th>
        <th class="col-md-1">
          Days to service
        </th>
        <th class="col-md-1">
          Kilometers to service
        </th>
        <th class="col-md-1 text-end">
        </th>
      </tr>
      </thead>
      <tbody>
      {% for car in car_list %}
        <tr>
          <td>
            {{ car.registration_number }}
          </td>
          <td>
            {{ car.manufacturer }}
          </td>
          <td>
            {{ car.model }}
          </td>
          <td>
            {{ car.mileage }}
          </td>
          <td>
            {{ car.days_to_service }}
          </td>
          <td>
            {{ car.kilometers_to_service }} km ({{ car.next_service_mileage }} km)
          </td>
          <td class="col-md-1 text-end">
            <a href="{% url 'client-car-detail-view' car.pk %}">
              <i class="fas fa-external-link-alt"></i>
            </a>
          </td>
        </tr>
      {% endfor %}
      </tbody>
    </table>
  </div>
{% endblock %}